-- Candidate metadata is bounded before document hydration in the search query.
-- The existing documents_search_vector_idx remains the durable full-text index.
-- This migration is metadata-only because PostgreSQL rejects the proposed
-- expression index: the text-search expression is not immutable.
